version: '3.7'

services:
    dbpeguin:
        image: postgres
        container_name: postgres_iris
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=data_iris
            - PGDATA=/var/lib/postgresql/data/pgdata
        volumes:
             - /apps/data:/var/lib/postgresql/data/pgdata
        ports:
          - "5432:5432"
