version: "3.7"

services:

  flask:
    build: ./flask
    container_name: ApiPenguin
    restart: always
    environment:
      - APP_NAME=MyFlaskApp
    expose:
      - 8080
    networks:
      - proxynet
   

  nginx:
    build: ./nginx
    container_name: NginxMicroservice
    restart: always
    ports:
      - "9090:9090"
    networks:
      - proxynet
    expose:
      - "9090"


networks:
  proxynet:
    name: custom_network

     
