swagger: '2.0'
summary: "Predicción de especie de pingüino"
description: "Esta es un API que predice la especie de pingüino"
consumes:
- "application/json"
produces:
- "application/json"
parameters:
- in: "body"
  name: "body"
  description: "Predice la especie de pingüino en base a sus características"
  required: true
  schema:
    type: "object"
    properties:
      culmen_length_mm:
        type: number
        description: Longitud del pico en mm
        example: 0.09090909
        order: 1
        x-order: 1
      culmen_depth_mm:
        type: number
        description: Profundidad del pico en mm
        example: 0.95238095
        order: 2
        x-order: 2
      flipper_length_mm:
        type: number
        description: Longitud de la aleta en mm
        example: 0.44067797
        order: 3
        x-order: 3
      body_mass_g:
        type: number
        description: Masa del pingüino en g
        example: 0.47222222
        order: 4
        x-order: 4

responses:
  405:
    description: "Invalid input"
